### PR TITLE
Add support for pseudofile

### LINKED ISSUE #8: [Feature request] Pass a pseudofile to officedissector.doc.Document
I'm writing a script to process email attachments and I don't want to touch the disk so I need a way to pass a pseudo file (BytesIO).

It doesn't seems particularly difficult to implement and won't change much of the logic so I may just do a pull requests soon-ish.

### PR DESCRIPTION
**Pull request by Rafiot**
Fix #8

### CODE REVIEW

**Comment by Rafiot** [comment]
FYI, I successfully use this code in this project: https://github.com/CIRCL/PyCIRCLean/blob/mail/bin/mail.py#L272

**Comment by Rafiot** [comment]
Should I consider this projected unmaintained and use my repo as master from now on?

**Comment by naegelejd** [comment]
No, I apologize, I haven't received notifications for your pull requests. I'm going to merge each one in chronological order.

**Comment by naegelejd** [comment]
OK, we're caught up. Sorry for the delay. I've made sure I'll receive future notifications.

**Comment by Rafiot** [comment]
Nice, thanks!

**Pull request merged**
