### PR TITLE
Add travis support, make code compatible with python3

### PR DESCRIPTION
**Pull request by Rafiot**

### CODE REVIEW

**Comment by dovi5988** [comment]
Raphaël,

1) Thank you.
2) Did you test on Python 2.7 and did all the tests still pass?

**Comment by Rafiot** [comment]
All the test that are run on travis (`smoke_tests.SmokeTest`) still pass: https://travis-ci.org/Rafiot/officedissector

I was not able to run `test_plugin_performance.py`, because `mas.py` isn't in the repository. The content of `test/unit_test` isn't run either because I didn't know if they were still relevant, and why they are in a sub directory. But I can add them if they are supposed to be used.

**Comment by Rafiot** [comment]
up?

**Comment by dovi5988** [comment]
Can you send me your email so I can contact direct?

**Comment by Rafiot** [comment]
sure: raphael.vinot gmail.com

**Comment by Rafiot** [comment]
Looks good. What do you think? 

https://codecov.io/github/Rafiot/officedissector?branch=travis
https://travis-ci.org/Rafiot/officedissector/builds/106284727
https://coveralls.io/github/Rafiot/officedissector

**Comment by naegelejd** [comment]
Hi @Rafiot, I'm now maintaining officedissector. Give me a couple days to familiarize myself with the tests and review your PR then I'll merge. Just a heads up, I'll probably ask you to squash any commits that can be logically grouped together.

**Comment by Rafiot** [comment]
That make total sense, the last 10 commits were lots of messing around to get travis to stop complaining. 
I think 3 commits should be enough:
- 2to3 
- travis
- Changes in tests

**Comment by naegelejd** [comment]
Is it necessary for the Travis config to rely on your branch of MASTIFF? I'm aware that the tests need some attention regarding MASTIFF, but until we fix those issues the unit tests will suffice for Travis.

Also, if you believe that it's better to install MASTIFF before running the tests can you update `test_plugin_performance.py` to work the same way as `test_plugins.py` to maintain consistency.

I hope to address the issues with MASTIFF compatibility soon.

**Comment by Rafiot** [comment]
This is the difference: https://github.com/KoreLogicSecurity/mastiff/pull/1/files
The reason is that mastiff needs to be installed as root because it tries to install the config file in /etc and if I sudo install, the travis virtualenv gets confused... Also the old yapsy version is fucked up.

**Comment by Rafiot** [comment]
@naegelejd Can I do anything to help you merge this pull request?

**Comment by naegelejd** [comment]
Well I can merge the 2to3 changes anytime if you either 1) organize and squash the commits, or 2) split into multiple PRs.

I understand the changes to MASTIFF, however our Travis config can't depend on your fork. If you'd like we could fork MASTIFF under our organization until they merge your PR.

The other problem, of course, is that I need to fix the tests using MASTIFF so they work. In order to do that I have to get a working `yara` Python module, which your MASTIFF Travis config does not install. You install `yara` and `yara-python`, but that's different from [this](https://pypi.python.org/pypi/yara) aka [this](https://github.com/mjdorma/yara-ctypes), which is also needed and is no longer compatible with `yara` proper.

**Comment by Rafiot** [comment]
Done. As you can see, the port to python3 of the module is fairly simple (only the print statements).

I created an other PR for the tests, but feel free to do it differently if you prefer. Regarding Yara, the pip package is very much outdated and the recommended python yara package is there nowadays: http://yara.readthedocs.org/en/v3.4.0/gettingstarted.html#compiling-and-installing-yara

**Pull request closed without merging**
